server:
  port: 8092

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://20.0.3.106:3306/oauth2?characterEncodeing=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      filter:
        stat:
          enabled: false
  redis:
    database: 15
    host: 20.0.0.252
    port: 6379
    password: saftop9854
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://auth-server:8090/oauth2/keys

oauth:
  token:
    store:
      strategy: JDBC # MEMORY,JDBC,JWT,REDIS