spring:
  application:
    name: spring-boot-oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: false
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/oauth2?characterEncodeing=utf-8&useSSL=false&serverTimezone=GMT
    username: root
  redis:
    database: 0    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 1
    password: password
    port: 6379
    timeout: 3000
logging:
  file:
    name: ./log/run.log
oauth2:
  jwt-secret: sunny_zhy
