server:
  port: 8080
  session:
    cookie:
      name: SESSIONID

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://20.0.0.106:3306/client?characterEncodeing=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      filter:
        stat:
          enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  oauth2:
    client:
      client-auth-code:
        client-id: messaging-client
        client-secret: user
        grant-type: authorization_code
        user-authorization-uri: http://auth-server:8090/oauth/authorize
        access-token-uri: http://auth-server:8090/oauth/token
        scope: read, write
        pre-established-redirect-uri: http://localhost:8080/auth
        use-current-uri: false

messages:
  base-uri: http://localhost:8092/message
